import { useRef, useState, useCallback, useEffect } from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { DEFAULT_PNPKI_CONFIG, PNPKIConfig } from './usePNPKI';
import {
  CheckCircle2Icon,
  EyeIcon,
  EyeOffIcon,
  GripVertical,
  KeyRoundIcon,
  LoaderIcon,
  Trash2Icon,
  UploadIcon,
} from 'lucide-react';

interface Props {
  open: boolean;
  onClose: () => void;
  config: PNPKIConfig;
  onSave: (cfg: PNPKIConfig) => Promise<void>;
  onClear: () => void;
  /** Live DTR PDF blob to preview — generated by PrintDTR when the dialog opens */
  pdfBlob?: Blob | null;
  /** Total pages in the PDF — enables the Page to Sign selector */
  totalPages?: number;
}

// ── pdfjs CDN loader (no npm package needed) ──────────────────────────────────
let _pdfjs: any = null;
function loadPdfJs(): Promise<any> {
  if (_pdfjs) return Promise.resolve(_pdfjs);
  if ((window as any).pdfjsLib) {
    _pdfjs = (window as any).pdfjsLib;
    return Promise.resolve(_pdfjs);
  }
  return new Promise((resolve, reject) => {
    const s = document.createElement('script');
    s.src = 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js';
    s.onload = () => {
      const lib = (window as any).pdfjsLib;
      lib.GlobalWorkerOptions.workerSrc =
        'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
      _pdfjs = lib;
      resolve(lib);
    };
    s.onerror = reject;
    document.head.appendChild(s);
  });
}

// ── helpers ───────────────────────────────────────────────────────────────────
function fileToBase64(file: File): Promise<string> {
  return new Promise((res, rej) => {
    const r = new FileReader();
    r.onload = () => res((r.result as string).split(',')[1]);
    r.onerror = rej;
    r.readAsDataURL(file);
  });
}

// ── Signature placement canvas with live PDF preview ─────────────────────────
interface CanvasProps {
  xRatio: number;
  yRatio: number;
  wRatio: number;
  hRatio: number;
  onChange: (x: number, y: number, w: number, h: number) => void;
  /** Rendered page number (1-based) */
  pageNum?: number;
  /** PDF blob to preview in the background */
  pdfBlob?: Blob | null;
  /** Signature appearance fields */
  signerName?: string;
  signNote?: string;   // kept for internal prop name; maps to signerPosition
  signImageBase64?: string;
  /** Content position & scale within the sig box */
  signTextScale?: number;
  signTextOffsetX?: number;
  signTextOffsetY?: number;
  signImageScale?: number;
  signImageOffsetX?: number;
  signImageOffsetY?: number;
  onContentChange?: (offsetX: number, offsetY: number, scale: number, type: 'text' | 'image') => void;
  /** Text appearance */
  sigFontSize?: number;
  sigFontFamily?: string;
  sigTextColor?: string;
}

function SigCanvas({
  xRatio, yRatio, wRatio, hRatio, onChange,
  pageNum = 1, pdfBlob, signerName, signNote, signImageBase64,
  signTextScale = 1, signTextOffsetX = 0, signTextOffsetY = 0,
  signImageScale = 1, signImageOffsetX = 0, signImageOffsetY = 0,
  onContentChange,
  sigFontSize = 10, sigFontFamily = 'Arial, sans-serif', sigTextColor = '#1e3a5f',
}: CanvasProps) {
  const containerRef  = useRef<HTMLDivElement>(null);
  const bgCanvasRef   = useRef<HTMLCanvasElement>(null);
  const [pdfLoading, setPdfLoading] = useState(false);
  const [pdfReady,   setPdfReady]   = useState(false);
  // Track container height so font scales proportionally to the sig box
  const [containerH, setContainerH] = useState(0);
  useEffect(() => {
    const el = containerRef.current;
    if (!el) return;
    const ro = new ResizeObserver((entries) => setContainerH(entries[0].contentRect.height));
    ro.observe(el);
    return () => ro.disconnect();
  }, []);

  const dragging        = useRef<{ startX: number; startY: number; origX: number; origY: number } | null>(null);
  const resizing        = useRef<{ startX: number; startY: number; origW: number; origH: number } | null>(null);
  const contentDragging = useRef<{ startX: number; startY: number; origOX: number; origOY: number; type: 'text' | 'image' } | null>(null);

  const clamp = (v: number, lo: number, hi: number) => Math.max(lo, Math.min(hi, v));

  // ── render PDF page onto background canvas ────────────────────────────────
  useEffect(() => {
    if (!pdfBlob) { setPdfReady(false); return; }
    let cancelled = false;
    setPdfLoading(true);
    setPdfReady(false);

    (async () => {
      try {
        const pdfjs = await loadPdfJs();
        if (cancelled) return;

        const ab  = await pdfBlob.arrayBuffer();
        const doc = await pdfjs.getDocument({ data: ab }).promise;
        const pg  = await doc.getPage(Math.min(pageNum, doc.numPages));
        if (cancelled) return;

        const canvas = bgCanvasRef.current;
        if (!canvas) return;

        const containerW = containerRef.current?.clientWidth || 420;
        const raw        = pg.getViewport({ scale: 1 });
        const scale      = containerW / raw.width;
        const vp         = pg.getViewport({ scale });

        canvas.width  = vp.width;
        canvas.height = vp.height;

        const ctx = canvas.getContext('2d')!;
        await pg.render({ canvasContext: ctx, viewport: vp }).promise;

        if (!cancelled) { setPdfReady(true); setPdfLoading(false); }
      } catch (err) {
        console.warn('PDF preview failed:', err);
        if (!cancelled) setPdfLoading(false);
      }
    })();

    return () => { cancelled = true; };
  }, [pdfBlob, pageNum]);

  // ── drag / resize ─────────────────────────────────────────────────────────
  const onMouseDownBox = useCallback(
    (e: React.MouseEvent) => {
      e.preventDefault(); e.stopPropagation();
      dragging.current = { startX: e.clientX, startY: e.clientY, origX: xRatio, origY: yRatio };
    },
    [xRatio, yRatio]
  );

  const onMouseDownResize = useCallback(
    (e: React.MouseEvent) => {
      e.preventDefault(); e.stopPropagation();
      resizing.current = { startX: e.clientX, startY: e.clientY, origW: wRatio, origH: hRatio };
    },
    [wRatio, hRatio]
  );

  const onMouseDownTextContent = useCallback(
    (e: React.MouseEvent) => {
      e.preventDefault(); e.stopPropagation();
      contentDragging.current = { startX: e.clientX, startY: e.clientY, origOX: signTextOffsetX, origOY: signTextOffsetY, type: 'text' };
    },
    [signTextOffsetX, signTextOffsetY]
  );

  const onMouseDownImageContent = useCallback(
    (e: React.MouseEvent) => {
      e.preventDefault(); e.stopPropagation();
      contentDragging.current = { startX: e.clientX, startY: e.clientY, origOX: signImageOffsetX, origOY: signImageOffsetY, type: 'image' };
    },
    [signImageOffsetX, signImageOffsetY]
  );

  useEffect(() => {
    const onMove = (e: MouseEvent) => {
      if (!containerRef.current) return;
      const rect = containerRef.current.getBoundingClientRect();
      if (dragging.current) {
        const dx = (e.clientX - dragging.current.startX) / rect.width;
        const dy = (e.clientY - dragging.current.startY) / rect.height;
        onChange(
          clamp(dragging.current.origX + dx, 0, 1 - wRatio),
          clamp(dragging.current.origY + dy, 0, 1 - hRatio),
          wRatio, hRatio
        );
      }
      if (resizing.current) {
        const dw = (e.clientX - resizing.current.startX) / rect.width;
        const dh = (e.clientY - resizing.current.startY) / rect.height;
        onChange(xRatio, yRatio,
          clamp(resizing.current.origW + dw, 0.05, 1 - xRatio),
          clamp(resizing.current.origH + dh, 0.02, 1 - yRatio)
        );
      }
      if (contentDragging.current && onContentChange) {
        const boxW = rect.width  * wRatio;
        const boxH = rect.height * hRatio;
        const dx = (e.clientX - contentDragging.current.startX) / boxW;
        const dy = (e.clientY - contentDragging.current.startY) / boxH;
        const { type } = contentDragging.current;
        const scale = type === 'image' ? signImageScale : signTextScale;
        onContentChange(
          clamp(contentDragging.current.origOX + dx, 0, 1),
          clamp(contentDragging.current.origOY + dy, 0, 1),
          scale,
          type
        );
      }
    };
    const onUp = () => { dragging.current = null; resizing.current = null; contentDragging.current = null; };
    window.addEventListener('mousemove', onMove);
    window.addEventListener('mouseup', onUp);
    return () => { window.removeEventListener('mousemove', onMove); window.removeEventListener('mouseup', onUp); };
  }, [xRatio, yRatio, wRatio, hRatio, onChange, onContentChange, signImageBase64, signImageScale, signTextScale]);

  const pct = (v: number) => `${(v * 100).toFixed(2)}%`;
  // sigFontSize is % of sig-box height — compute actual px for preview
  const sigBoxH   = (containerH || 200) * hRatio;
  const fontPx    = Math.max(4, sigFontSize / 100 * sigBoxH) * signTextScale;

  return (
    <div className="flex flex-col gap-1 flex-1 min-h-0">
      <p className="text-xs text-muted-foreground text-center select-none">
        Drag box to reposition · <span className="font-bold">⌟</span> corner to resize · drag <span className="font-bold">content inside</span> to move text/image
      </p>

      {/* ── Canvas container ── */}
      <div
        ref={containerRef}
        className="relative w-full border border-gray-300 shadow-inner select-none overflow-hidden bg-white"
        style={pdfReady ? {} : { aspectRatio: '1 / 1.414' }}
      >
        {/* PDF background */}
        <canvas
          ref={bgCanvasRef}
          className="block w-full"
          style={{ display: pdfReady ? 'block' : 'none' }}
        />

        {/* Fallback blank page (shown before PDF loads) */}
        {!pdfReady && (
          <div className="absolute inset-0 bg-white">
            {[0.25, 0.5, 0.75].map((v) => (
              <div key={`h${v}`} className="absolute w-full border-t border-dashed border-gray-100"
                style={{ top: pct(v) }} />
            ))}
            {[0.25, 0.5, 0.75].map((v) => (
              <div key={`v${v}`} className="absolute h-full border-l border-dashed border-gray-100"
                style={{ left: pct(v) }} />
            ))}
          </div>
        )}

        {/* Loading spinner */}
        {pdfLoading && (
          <div className="absolute inset-0 flex items-center justify-center bg-white/70 z-10">
            <LoaderIcon className="w-5 h-5 animate-spin text-blue-500" />
            <span className="ml-2 text-xs text-muted-foreground">Loading PDF…</span>
          </div>
        )}

        {/* ── Overlay: signature box ── */}
        <div className="absolute inset-0 pointer-events-none">
          <div
            onMouseDown={onMouseDownBox}
            className="absolute border-2 border-blue-400 border-dashed rounded cursor-move overflow-hidden"
            style={{
              left: pct(xRatio), top: pct(yRatio),
              width: pct(wRatio), height: pct(hRatio),
              pointerEvents: 'all',
              background: 'rgba(255,255,255,0.5)',
            }}
          >
            {/* ── Drag handle bar ── */}
            <div
              onMouseDown={onMouseDownBox}
              className="absolute top-0 left-0 right-0 flex items-center justify-center z-20"
              style={{
                height: 14,
                background: 'rgba(59,130,246,0.75)',
                cursor: 'move',
                pointerEvents: 'all',
              }}
            >
              <GripVertical className="rotate-90" style={{ width: 12, height: 12, color: 'white', opacity: 0.9 }} />
            </div>
            {/* ── Signature appearance preview ── */}
            <div className="w-full h-full relative overflow-hidden" style={{ paddingTop: 14 }}>
              {signImageBase64 && (
                <img
                  src={`data:image/png;base64,${signImageBase64}`}
                  draggable={false}
                  onMouseDown={onMouseDownImageContent}
                  style={{
                    position: 'absolute',
                    left: `${signImageOffsetX * 100}%`,
                    top:  `${signImageOffsetY * 100}%`,
                    width:  `${signImageScale * 100}%`,
                    height: `${signImageScale * 100}%`,
                    objectFit: 'contain',
                    cursor: 'grab',
                    pointerEvents: 'all',
                  }}
                />
              )}
              <div
                onMouseDown={onMouseDownTextContent}
                className="absolute flex flex-col px-1"
                style={{
                  left: `${signTextOffsetX * 100}%`,
                  top:  `${signTextOffsetY * 100}%`,
                    fontSize: `${fontPx}px`,
                  fontFamily: sigFontFamily,
                  lineHeight: 1.35,
                  color: sigTextColor,
                  cursor: 'grab',
                  pointerEvents: 'all',
                  userSelect: 'none',
                  whiteSpace: 'nowrap',
                }}
              >
                <span style={{ fontWeight: 700 }}>{signerName || 'Signer Name'}</span>
                {signNote && <span>{signNote}</span>}
              </div>
            </div>

            {/* Resize handle */}
            <div
              onMouseDown={onMouseDownResize}
              className="absolute bottom-0 right-0 w-3 h-3 bg-blue-600 cursor-se-resize rounded-tl z-10"
              style={{ lineHeight: '12px', textAlign: 'center', fontSize: 8, color: 'white' }}
            >
              ⌟
            </div>
          </div>
        </div>
      </div>

      {/* Numeric readout */}
      <div className="grid grid-cols-4 gap-1 text-[10px] text-muted-foreground text-center">
        {[['X', xRatio], ['Y', yRatio], ['W', wRatio], ['H', hRatio]].map(([label, value]) => (
          <div key={label as string} className="bg-muted rounded px-1 py-0.5">
            <span className="font-mono">{label}: {Number(value).toFixed(3)}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

// ─── Main dialog ──────────────────────────────────────────────────────────────
export default function PNPKISetup({ open, onClose, config, onSave, onClear, pdfBlob, totalPages = 1 }: Props) {
  const [draft, setDraft] = useState<PNPKIConfig>(config);
  const [showPass, setShowPass] = useState(false);
  const [p12Error, setP12Error] = useState('');
  const [sigImgPreview, setSigImgPreview] = useState<string | null>(null);

  // Sync when parent config changes (e.g. clear)
  useEffect(() => setDraft(config), [config]);

  // Rebuild preview when config arrives with a saved image
  useEffect(() => {
    if (config.signImageBase64) {
      setSigImgPreview(`data:image/png;base64,${config.signImageBase64}`);
    }
  }, [config.signImageBase64]);

  const set = <K extends keyof PNPKIConfig>(key: K, value: PNPKIConfig[K]) =>
    setDraft((d) => ({ ...d, [key]: value }));

  // ── P12 file ──
  const handleP12 = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    if (!file.name.match(/\.(p12|pfx)$/i)) {
      setP12Error('Please select a .p12 or .pfx file.');
      return;
    }
    setP12Error('');
    const b64 = await fileToBase64(file);
    setDraft((d) => ({ ...d, p12Base64: b64, fileName: file.name, enabled: true }));
  };

  // ── Sig image ──
  const handleSigImage = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const b64 = await fileToBase64(file);
    setSigImgPreview(`data:image/png;base64,${b64}`);
    setDraft((d) => ({ ...d, signImageBase64: b64, signImageFileName: file.name }));
  };

  const clearSigImage = () => {
    setSigImgPreview(null);
    setDraft((d) => ({ ...d, signImageBase64: undefined, signImageFileName: undefined }));
  };

  const handleCanvasChange = useCallback(
    (x: number, y: number, w: number, h: number) =>
      setDraft((d) => ({ ...d, xRatio: x, yRatio: y, wRatio: w, hRatio: h })),
    []
  );

  const handleContentChange = useCallback(
    (offsetX: number, offsetY: number, scale: number, type: 'text' | 'image') =>
      setDraft((d) =>
        type === 'image'
          ? { ...d, signImageOffsetX: offsetX, signImageOffsetY: offsetY, signImageScale: scale }
          : { ...d, signTextOffsetX: offsetX, signTextOffsetY: offsetY, signTextScale: scale }
      ),
    []
  );

  const handleSave = async () => {
    if (!draft.p12Base64) {
      setP12Error('Please upload a P12/PFX certificate first.');
      return;
    }
    await onSave({ ...draft, enabled: true });
    onClose();
  };

  const handleClear = () => {
    setSigImgPreview(null);
    setDraft(DEFAULT_PNPKI_CONFIG);
    setP12Error('');
    onClear();
    onClose();
  };

  const isConfigured = !!config.p12Base64 && config.enabled;

  return (
    <Dialog open={open} onOpenChange={(v) => !v && onClose()}>
      <DialogContent className="max-w-4xl w-full max-h-[92vh] flex flex-col">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <KeyRoundIcon className="w-5 h-5 text-blue-500" />
            PNPKI Digital Signature Setup
            {isConfigured && (
              <span className="ml-2 inline-flex items-center gap-1 text-xs font-normal text-green-600 bg-green-50 border border-green-200 rounded-full px-2 py-0.5">
                <CheckCircle2Icon className="w-3 h-3" /> Configured
              </span>
            )}
          </DialogTitle>
        </DialogHeader>

        {/* ─ Two-column layout ─ */}
        <div className="flex flex-row md:flex-col gap-4 overflow-y-auto flex-1 min-h-0 pr-1">

          {/* ── LEFT: placement canvas (hidden on small screens) ─────── */}
          <div className="flex md:hidden flex-1 flex-col gap-2 min-h-0 min-w-0">
            <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">
              Signature Placement <span className="normal-case font-normal text-gray-400">(drag to move, corner to resize)</span>
            </label>

            <SigCanvas
              xRatio={draft.xRatio}
              yRatio={draft.yRatio}
              wRatio={draft.wRatio}
              hRatio={draft.hRatio}
              onChange={handleCanvasChange}
              pdfBlob={pdfBlob}
              pageNum={draft.page}
              signerName={draft.signerName}
              signNote={draft.signerPosition}
              signImageBase64={draft.signImageBase64}
              signTextScale={draft.signTextScale ?? 1}
              signTextOffsetX={draft.signTextOffsetX ?? 0}
              signTextOffsetY={draft.signTextOffsetY ?? 0}
              signImageScale={draft.signImageScale ?? 1}
              signImageOffsetX={draft.signImageOffsetX ?? 0}
              signImageOffsetY={draft.signImageOffsetY ?? 0}
              onContentChange={handleContentChange}
              sigFontSize={draft.sigFontSize ?? 8}
              sigFontFamily={draft.sigFontFamily ?? 'Arial, sans-serif'}
              sigTextColor={draft.sigTextColor ?? '#1e3a5f'}
            />


          </div>

          {/* ── RIGHT: settings ─────────────────────────────────── */}
          <div className="flex flex-col gap-3 w-72 md:w-full shrink-0 overflow-y-auto">

            {/* P12 / PFX */}
            <div>
              <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">
                P12 / PFX Certificate *
              </label>
              <label className="mt-1 flex items-center gap-2 cursor-pointer border border-dashed border-gray-300 rounded-md p-2 hover:border-blue-400 transition-colors">
                <UploadIcon className="w-4 h-4 shrink-0 text-blue-500" />
                <span className="text-sm truncate text-muted-foreground">
                  {draft.fileName || 'Click to upload…'}
                </span>
                <input
                  type="file"
                  accept=".p12,.pfx"
                  className="sr-only"
                  onChange={handleP12}
                />
              </label>
              {p12Error && <p className="text-xs text-red-500 mt-0.5">{p12Error}</p>}
              {draft.fileName && !p12Error && (
                <p className="text-xs text-green-600 mt-0.5 truncate">✓ {draft.fileName}</p>
              )}
            </div>

            {/* Password */}
            <div>
              <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">
                P12 Password
              </label>
              <div className="relative mt-1">
                <input
                  type={showPass ? 'text' : 'password'}
                  className="w-full border border-gray-300 rounded-md px-3 py-1.5 text-sm outline-none focus:border-blue-400 pr-8"
                  placeholder="Leave blank if none"
                  value={draft.password}
                  onChange={(e) => set('password', e.target.value)}
                />
                <button
                  type="button"
                  className="absolute right-2 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
                  onClick={() => setShowPass((v) => !v)}
                >
                  {showPass ? <EyeOffIcon className="w-3.5 h-3.5" /> : <EyeIcon className="w-3.5 h-3.5" />}
                </button>
              </div>
            </div>

            {/* Signer name */}
            <div>
              <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">
                Signer Name
              </label>
              <input
                type="text"
                className="mt-1 w-full border border-gray-300 rounded-md px-3 py-1.5 text-sm outline-none focus:border-blue-400"
                placeholder="Optional override"
                value={draft.signerName}
                onChange={(e) => set('signerName', e.target.value)}
              />
            </div>

            {/* Signer position */}
            <div>
              <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">
                Signer Position
              </label>
              <input
                type="text"
                className="mt-1 w-full border border-gray-300 rounded-md px-3 py-1.5 text-sm outline-none focus:border-blue-400"
                placeholder="e.g. IT Officer"
                value={draft.signerPosition}
                onChange={(e) => set('signerPosition', e.target.value)}
              />
            </div>

            {/* Text appearance */}
            <div className="border border-gray-200 rounded-md p-2 flex flex-col gap-2">
              <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">Text Appearance</label>

              {/* Font size */}
              <div>
                <div className="flex justify-between">
                  <span className="text-xs text-muted-foreground">Font Size</span>
                  <span className="text-xs font-mono text-muted-foreground">{draft.sigFontSize ?? 10}% of box</span>
                </div>
                <input
                  type="range" min="2" max="30" step="1"
                  className="w-full accent-blue-500"
                  value={draft.sigFontSize ?? 10}
                  onChange={(e) => set('sigFontSize', parseInt(e.target.value))}
                />
              </div>

              {/* Font family */}
              <div>
                <span className="text-xs text-muted-foreground block mb-1">Font</span>
                <select
                  className="w-full border border-gray-300 rounded-md px-2 py-1 text-xs outline-none focus:border-blue-400 bg-background"
                  value={draft.sigFontFamily ?? 'Arial, sans-serif'}
                  onChange={(e) => set('sigFontFamily', e.target.value)}
                >
                  <option value="Arial, sans-serif">Arial</option>
                  <option value="'Segoe UI', Arial, sans-serif">Segoe UI</option>
                  <option value="'Times New Roman', Times, serif">Times New Roman</option>
                  <option value="Georgia, serif">Georgia</option>
                  <option value="'Courier New', Courier, monospace">Courier New</option>
                  <option value="cursive">Cursive</option>
                </select>
              </div>

              {/* Text color */}
              <div className="flex items-center gap-2">
                <span className="text-xs text-muted-foreground flex-1">Color</span>
                <input
                  type="color"
                  className="w-8 h-7 rounded cursor-pointer border border-gray-300"
                  value={draft.sigTextColor ?? '#1e3a5f'}
                  onChange={(e) => set('sigTextColor', e.target.value)}
                />
                <span className="text-xs font-mono text-muted-foreground">{draft.sigTextColor ?? '#1e3a5f'}</span>
              </div>
            </div>

            {/* Page to Sign (only shown when document has multiple pages) */}
            {totalPages > 1 && (
              <div>
                <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">
                  Page to Sign
                </label>
                <div className="flex items-center gap-2 mt-1">
                  <input
                    type="number"
                    min={1}
                    max={totalPages}
                    className="w-20 border border-gray-300 rounded-md px-3 py-1.5 text-sm outline-none focus:border-blue-400"
                    value={draft.page}
                    onChange={(e) => {
                      const v = Math.max(1, Math.min(totalPages, parseInt(e.target.value) || 1));
                      set('page', v);
                    }}
                  />
                  <span className="text-xs text-muted-foreground">of {totalPages}</span>
                </div>
              </div>
            )}

            {/* Signature image */}
            <div>
              <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">
                Signature Image (optional)
              </label>
              {sigImgPreview ? (
                <div className="mt-1 relative">
                  <img src={sigImgPreview} alt="sig" className="h-12 border rounded object-contain bg-gray-50" />
                  <button
                    type="button"
                    onClick={clearSigImage}
                    className="absolute top-0 right-0 bg-red-500 text-white rounded-full p-0.5 hover:bg-red-600"
                  >
                    <Trash2Icon className="w-3 h-3" />
                  </button>
                </div>
              ) : (
                <label className="mt-1 flex items-center gap-2 cursor-pointer border border-dashed border-gray-300 rounded-md p-2 hover:border-blue-400 transition-colors">
                  <UploadIcon className="w-4 h-4 shrink-0 text-muted-foreground" />
                  <span className="text-xs text-muted-foreground">Upload PNG / JPG</span>
                  <input
                    type="file"
                    accept="image/*"
                    className="sr-only"
                    onChange={handleSigImage}
                  />
                </label>
              )}
            </div>
            {/* Content scale & position reset */}
            {draft.signImageBase64 ? (
              <div>
                <div className="flex justify-between items-center">
                  <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">
                    Image Scale ({((draft.signImageScale ?? 1) * 100).toFixed(0)}%)
                  </label>
                  <button
                    type="button"
                    className="text-[10px] text-blue-500 hover:underline"
                    onClick={() => setDraft((d) => ({ ...d, signImageScale: 1, signImageOffsetX: 0, signImageOffsetY: 0 }))}
                  >
                    Reset
                  </button>
                </div>
                <input
                  type="range" min="0.3" max="2" step="0.05"
                  className="w-full mt-1 accent-blue-500"
                  value={draft.signImageScale ?? 1}
                  onChange={(e) => set('signImageScale', parseFloat(e.target.value))}
                />
                <p className="text-[10px] text-muted-foreground mt-0.5">Drag image in preview to reposition</p>
              </div>
            ) : (
              <div>
                <div className="flex justify-between items-center">
                  <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">
                    Text Scale ({((draft.signTextScale ?? 1) * 100).toFixed(0)}%)
                  </label>
                  <button
                    type="button"
                    className="text-[10px] text-blue-500 hover:underline"
                    onClick={() => setDraft((d) => ({ ...d, signTextScale: 1, signTextOffsetX: 0, signTextOffsetY: 0 }))}
                  >
                    Reset
                  </button>
                </div>
                <input
                  type="range" min="0.3" max="2.5" step="0.05"
                  className="w-full mt-1 accent-blue-500"
                  value={draft.signTextScale ?? 1}
                  onChange={(e) => set('signTextScale', parseFloat(e.target.value))}
                />
                <p className="text-[10px] text-muted-foreground mt-0.5">Drag text in preview to reposition</p>
              </div>
            )}
          </div>

        </div>

        {/* ─ Footer ─ */}
        <div className="flex justify-between items-center gap-2 pt-2 border-t">
          <Button
            type="button"
            variant="destructive"
            size="sm"
            className="gap-1"
            onClick={handleClear}
          >
            <Trash2Icon className="w-3.5 h-3.5" /> Clear
          </Button>
          <div className="flex gap-2">
            <Button type="button" variant="outline" size="sm" onClick={onClose}>
              Cancel
            </Button>
            <Button type="button" size="sm" onClick={handleSave} className="gap-1">
              <CheckCircle2Icon className="w-3.5 h-3.5" />
              Save &amp; Enable
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
